Feature/create
line23labs/to-do pull request #7
Opened 2019-08-21 06:03 UTC by Shirley-Liz

request a review

2019-08-21 07:24 UTC, edwinmp requested changes

2019-08-21 07:24 UTC, edwinmp commented on src/server/controllers/tasks.js
> +import { Task } from "../models/tasks";
I think you have some formatter that's going against our `eslint` ... please turn it off.
No spaces between the curly braces and quotes must be single, not double.

2019-08-21 07:24 UTC, edwinmp commented on src/server/controllers/tasks.js
> +   *
Add a description for this function.

2019-08-21 07:24 UTC, edwinmp commented on src/server/controllers/tasks.js
> +   * @param {*} [option={}]
Why is option an object when you're finding by ID?

2019-08-21 07:24 UTC, edwinmp commented on src/server/controllers/tasks.js
> +   * @param {*} [option={}]
Shouldn't be named option.

2019-08-21 07:24 UTC, edwinmp commented on src/server/controllers/tasks.js
> +        if (error.kind === "ObjectId") {
Single quotes

2019-08-21 07:24 UTC, edwinmp commented on src/server/controllers/tasks.js
> +  insertTask() {
Add a JSDoc.

2019-08-21 07:24 UTC, edwinmp commented on src/server/controllers/tasks.js
> +      console.log("error");
Don't think we need this.

2019-08-21 07:24 UTC, edwinmp commented on src/server/controllers/tasks.js
> +        console.log("error")
Or this.

2019-08-21 07:24 UTC, edwinmp commented on src/server/controllers/tasks.js
> +        let response = error.message;
Inline this.

2019-08-21 07:24 UTC, edwinmp commented on src/server/controllers/tasks.js
> +        console.log("error")
Don't need this.

2019-08-21 07:24 UTC, edwinmp commented on src/server/controllers/tasks.js
> +    // this.res.json(newTask);
Don't commit unnecessary comments.

2019-08-21 07:24 UTC, edwinmp commented on src/server/models/tasks.js
> +    type:String,
Space after `type:`

2019-08-21 07:24 UTC, edwinmp commented on src/server/models/tasks.js
> +    type:Date,
Space after `type:`

2019-08-21 07:24 UTC, edwinmp commented on src/server/models/tasks.js
> +import { toUnicode } from 'punycode';
What's the purpose of this?

2019-08-21 07:24 UTC, edwinmp commented on src/server/models/tasks.js
> +  {
Move to previous line.

2019-08-21 07:24 UTC, edwinmp commented on src/server/models/tasks.js
> +  date:{
Space after `date:`

2019-08-21 07:24 UTC, edwinmp commented on src/server/models/tasks.js
> +  email:{
Space after `email:`

2019-08-21 07:24 UTC, edwinmp commented on src/server/server.js
> +
Remove extra blank lines.

2019-08-22 07:17 UTC, Shirley-Liz commented
changes made

2019-08-22 09:55 UTC, edwinmp requested changes
There's some unresolved comments. Also, update your local `develop` branch, then switch back to this one and rebase `develop` ... i.e `git rebase develop` ... this will attempt to full the changes on the develop branch into yours ... you'll run into some conflicts... resolving them should be a good experience for you.

2019-08-22 09:55 UTC, edwinmp commented on .eslintrc.json
> -        "max-len": [ "error", { "code": 100 } ]
Why did you remove the rule? It served a purpose... revert

2019-08-22 09:55 UTC, edwinmp commented on .eslintrc.json
> +}
New line at the end of each file.

2019-08-23 11:27 UTC, Shirley-Liz commented
made changes

2019-08-27 07:59 UTC, edwinmp requested changes

2019-08-27 07:59 UTC, edwinmp commented on src/server/controllers/tasks.js
> +      console.log('error');
This console log serves no purpose.

2019-08-27 07:59 UTC, edwinmp commented on src/server/controllers/tasks.js
> +        console.log('error');
This one too...

2019-08-27 07:59 UTC, edwinmp commented on src/server/controllers/tasks.js
> +        console.log('error');
This one doesn't even make sense... there's no error here.

2019-08-29 09:22 UTC, edwinmp requested changes

2019-08-29 09:22 UTC, edwinmp commented on src/server/controllers/tasks.js
> -      }
You deleted vital error handling... please add it again. My comment referred ONLY to the console logs.

2019-09-16 10:09 UTC, edwinmp approved these changes

2019-09-16 10:12 UTC, priscanicktar approved these changes

2019-09-16 10:15 UTC, merged